### ISSUE TITLE
express-flash error during npm run start

### ISSUE THREAD

**Issue by nileshtrivedi** [mathigon/textbooks#448]
```
helix ~/code/textbooks [master] $ node -v
v16.15.1
helix ~/code/textbooks [master] $ npm -v
8.11.0
helix ~/code/textbooks [master] $ ts-node -v
v10.8.1


helix ~/code/textbooks [master] $ npm run start

> @mathigon/textbooks@0.7.3 start
> npm-run-all --parallel watch server


> @mathigon/textbooks@0.7.3 server
> mgon-serve


> @mathigon/textbooks@0.7.3 watch
> mgon-build --assets --watch --locales en

  ✔ Built icons.svg in 28ms
/Users/helix/code/textbooks/node_modules/ts-node/src/index.ts:843
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
node_modules/@mathigon/studio/server/app.ts:15:19 - error TS7016: Could not find a declaration file for module 'express-flash'. '/Users/helix/code/textbooks/node_modules/express-flash/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/express-flash` if it exists or add a new declaration (.d.ts) file containing `declare module 'express-flash';`

15 import flash from 'express-flash';
                     ~~~~~~~~~~~~~~~

    at createTSError (/Users/helix/code/textbooks/node_modules/ts-node/src/index.ts:843:12)
    at reportTSError (/Users/helix/code/textbooks/node_modules/ts-node/src/index.ts:847:19)
    at getOutput (/Users/helix/code/textbooks/node_modules/ts-node/src/index.ts:1057:36)
    at Object.compile (/Users/helix/code/textbooks/node_modules/ts-node/src/index.ts:1411:41)
    at Module.m._compile (/Users/helix/code/textbooks/node_modules/ts-node/src/index.ts:1596:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/helix/code/textbooks/node_modules/ts-node/src/index.ts:1600:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticCodes: [ 7016 ]
}
ERROR: "server" exited with 1.

```

**Comment by nileshtrivedi** [comment]
I had to do this to get this to work:

```
npm install -D @types/express-flash
npm install -D @types/bcryptjs
npm install -D @types/validator
npm install -D @types/pug
npm install -D @types/node-fetch
```

After this, I had to disable AirPlay Receiver service in Mac OS's Sharing settings to free up the port 5000.

**Comment by plegner** [comment]
Fixed in https://github.com/mathigon/textbooks/commit/c2a3fe80ed0b0f15ed07539509252772a2a2f520
